//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstrucaoCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCliente()
        {
            this.tblObra = new HashSet<tblObra>();
        }
    
        public int id_cliente { get; set; }
        public string nome { get; set; }
        public int nif { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string tipo { get; set; }
        public string cidade { get; set; }
        public string localidade { get; set; }
        public Nullable<int> telefone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblObra> tblObra { get; set; }
    }
}
