//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstrucaoCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFornecedor()
        {
            this.tblAbastece = new HashSet<tblAbastece>();
            this.tblFornece = new HashSet<tblFornece>();
        }
    
        public int id_fornecedor { get; set; }
        public string nif { get; set; }
        public string nome { get; set; }
        public string area { get; set; }
        public string servico { get; set; }
        public string cidade { get; set; }
        public string local { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string conta_bancaria { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAbastece> tblAbastece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFornece> tblFornece { get; set; }
    }
}
