//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstrucaoCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFuncionario()
        {
            this.tblPagamento = new HashSet<tblPagamento>();
            this.tblTrabalha = new HashSet<tblTrabalha>();
        }
    
        public int id_func { get; set; }
        public string nome { get; set; }
        public int bi { get; set; }
        public int nif { get; set; }
        public string cidade { get; set; }
        public string localidade { get; set; }
        public System.DateTime data_nascenca { get; set; }
        public string funcao { get; set; }
        public Nullable<int> telefone { get; set; }
        public string email { get; set; }
        public string conta_bancaria { get; set; }
        public Nullable<int> salario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool ehAdmin { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public Nullable<short> nivel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPagamento> tblPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrabalha> tblTrabalha { get; set; }
    }
}
