//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstrucaoCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblObra()
        {
            this.tblConsome = new HashSet<tblConsome>();
            this.tblPagamento = new HashSet<tblPagamento>();
            this.tblRequer = new HashSet<tblRequer>();
            this.tblTrabalha = new HashSet<tblTrabalha>();
        }
    
        public int id_obra { get; set; }
        public string nome { get; set; }
        public string local { get; set; }
        public int orçamento { get; set; }
        public string estado { get; set; }
        public System.DateTime data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public Nullable<int> custo_total { get; set; }
        public int id_cliente { get; set; }
        public string decriçao { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConsome> tblConsome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPagamento> tblPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequer> tblRequer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrabalha> tblTrabalha { get; set; }
    }
}
