//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstrucaoCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagamento
    {
        public int id_pagam { get; set; }
        public int quantia { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> id_obra { get; set; }
        public Nullable<int> id_func { get; set; }
        public string tipo { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual tblFuncionario tblFuncionario { get; set; }
        public virtual tblObra tblObra { get; set; }
    }
}
